/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_SIPRI_PB_H_INCLUDED
#define PB_SIPRI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DhtMessage {
    bool has_temperature;
    float temperature;
    bool has_humidity;
    float humidity;
    bool has_estadoServo;
    float estadoServo;
    bool has_estadoTapa;
    float estadoTapa;
} DhtMessage;


/* Initializer values for message structs */
#define DhtMessage_init_default                  {false, 0, false, 0, false, 0, false, 0}
#define DhtMessage_init_zero                     {false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DhtMessage_temperature_tag               1
#define DhtMessage_humidity_tag                  2
#define DhtMessage_estadoServo_tag               3
#define DhtMessage_estadoTapa_tag                4

/* Struct field encoding specification for nanopb */
#define DhtMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity,          2) \
X(a, STATIC,   OPTIONAL, FLOAT,    estadoServo,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    estadoTapa,        4)
#define DhtMessage_CALLBACK NULL
#define DhtMessage_DEFAULT NULL

extern const pb_msgdesc_t DhtMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DhtMessage_fields &DhtMessage_msg

/* Maximum encoded size of messages (where known) */
#define DhtMessage_size                          20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
